# file: mongodb/tasks/main.yml
---

- name: Install mongodb packages
  apt: pkg={{ item }}
  with_items:
    - mongodb
    - libmongo-client-dev
    - mongodb-server
    - mongodb-clients

- name: start mongodb service
  service: name=mongodb state=started enabled=yes

- name: install pymongo python module
  pip: name=pymongo


# Create User


- name: Create mongodb admin
  mongodb_user: database=admin
                name={{ mongodb_user }}
                password={{ mongodb_pass }}
                roles='dbAdminAnyDatabase,readWriteAnyDatabase,userAdminAnyDatabase,clusterAdmin'

- name: Create mongodb video
  mongodb_user: database=video
                name={{ mongodb_user }}
                password={{ mongodb_pass }}
                roles='dbAdmin,readWrite,userAdmin'

- name: Create mongodb {{ mongodb_name }}
  mongodb_user: database={{ mongodb_name }}
                name={{ mongodb_user }}
                password={{ mongodb_pass }}
                roles='dbAdmin,readWrite,userAdmin'


# Configurations


- name: replace mongodb.conf for bind_ip directive
  notify: restart mongodb
  lineinfile: dest=/etc/mongodb.conf
              regexp='^bind_ip = 127.0.0.1'
              line='bind_ip = 0.0.0.0'
              backrefs=yes

- name: replace mongodb.conf for auth directive
  notify: restart mongodb
  lineinfile: dest=/etc/mongodb.conf
              regexp='^#auth = true'
              line='auth = true'
              backrefs=yes  #' bugfix syntaxhighlight

- name: replace mongodb.conf for setParametera and enableLocalhostAuthBypass directive
  notify: restart mongodb
  lineinfile: dest=/etc/mongodb.conf
              regexp='^setParameter = enableLocalhostAuthBypass=0'
              line='setParameter = enableLocalhostAuthBypass=0'
              insertafter='^auth = true'  #' bugfix syntaxhighlight
