- name: Upgrade all packages
  yum: name=* state=latest

- name: Install the 'Development tools' package group(like build-essential in Ubuntu)
  yum: name="@Development tools" state=present

# Utility

- name: Install system utility
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - htop
    - git-all

# Secure: SSH Guardがパッチ見CentOSにはないためいれない


# AWS security groupでやるためいらない

- name: Install system utility
  service: name=firewalld state=stopped enabled=no
  ignore_errors: yes

# Selinux disabled

- command: setenforce 0
  ignore_errors: yes
- name: disabled selinux
  ignore_errors: yes
  lineinfile: dest=/etc/sysconfig/selinux
              regexp='^SELINUX=enforcing'
              line='SELINUX=disabled'
              backrefs=yes
