# file: memcached/handlers/main.yml
---

- name: restart memcached
  service: name=memcached state=restarted
  become: yes

- name: reload memcached
  service: name=memcached state=reloaded
  become: yes
