- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: restart redis
  service: name=redis state=restarted
  sudo: yes

- name: restart memcached
  service: name=memcached state=restarted
  sudo: yes
