# file: elasticsearch/handlers/main.yml
---

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  sudo: yes

- name: reload elasticsearch
  service: name=elasticsearch state=reloaded
  sudo: yes
