# file: elasticsearch/handlers/main.yml
---

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  become: yes

- name: reload elasticsearch
  service: name=elasticsearch state=reloaded
  become: yes
