---

- name: Add ClientAliveInterval directive into sshd_config for capistrano migration
  lineinfile: "dest=/etc/ssh/sshd_config
               regexp='^ClientAliveInterval 30'
               line='ClientAliveInterval 30'
               insertafter='^#UseLogin no'"
  notify: restart sshd


- name: Install based libraries for rails
  apt: pkg={{ item }}
  with_items:
    - nodejs

# unicorn

- name: Add unicorn configuration for upstart.
  template: src=video-unicorn.conf.j2
            dest=/etc/init/video-unicorn.conf

- name: register video-unicorn service
  service: name=video-unicorn state=started enabled=yes
